# Generated by Django 4.1.7 on 2023-02-20 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='upddated',
            new_name='updated',
        ),
    ]
