# Generated by Django 4.1.7 on 2023-02-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_rename_upddated_servicio_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispElec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidades', models.CharField(choices=[('Ef', 'bolivianos'), ('Ol', 'Dolares')], default='Ef', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tutoriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('link', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
