# Generated by Django 4.1.7 on 2023-02-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_dispelec_tutoriales'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispelec',
            name='disponible',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
